apiVersion: apps/v1
kind: Deployment
metadata:
  name: restore-deployment
spec:
  selector:
    matchLabels:
      app: restore
  replicas: 2
  template:
    metadata:
      labels:
        app: restore
    spec:
      containers:
        - name: restore
          image: jpcassidy/restoreonkubernetes:v1.0
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: restore-service
spec:
  selector:
    app: restore
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30008
  type: NodePort
